name: Check Notebooks

on: [push, pull_request]

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate notebooks format
        run: |
          pip install nbformat
          python -c "import nbformat; nbformat.read('notebooks/01_bronze_ingestion.ipynb', as_version=4)"
